# General app configuration
app:
  traverse:
    strategy: BFS # Valid values: BFS | DFS
    #startingUser: user
  twitter:
    accessSecret: ${twitter.accessSecret}
    accessToken: ${twitter.accessToken}
    consumerKey:  ${twitter.consumerKey}
    consumerSecret: ${twitter.consumerSecret}